import CaseStudyPage from "@/components/work/case-study-page";

export default function AllSuspectsCaseStudyPage() {
  return (
    <CaseStudyPage
      data={{
        category: "AI Mystery Game",
        title: "All Suspects",
        subtitle: "An immersive AI mystery game where every case is uniquely generated.",
        description:
          "Every case is uniquely generated by AI. Players interrogate suspects, examine evidence, and solve procedurally-generated detective mysteries. Built with Claude AI for dynamic storytelling.",
        timeline: "3 weeks from concept to launch",
        challenge:
          "Creating truly unique, solvable mysteries every time, not just random content but coherent narratives with real clues.",
        solution:
          "We built a multi-agent AI pipeline where one agent writes the mystery, another generates visuals, and a third validates solvability before delivery.",
        techStack: [
          "Next.js",
          "Claude AI (Anthropic)",
          "fal.ai (video generation)",
          "Railway",
          "Tailwind CSS",
        ],
        keyFeatures: [
          "AI-generated mysteries",
          "Dynamic suspect interrogation",
          "Evidence examination",
          "Video scene generation",
          "Multiple difficulty levels",
        ],
        projectUrl: "https://allsuspects.slateworks.io",
        heroImage: "/images/allsuspects-hero.jpg",
        heroOverlayClassName:
          "bg-gradient-to-br from-black/90 via-zinc-950/85 to-zinc-900/70",
        galleryImages: [
          { src: "/images/allsuspects-gameplay.jpg", caption: "AI-powered suspect interrogation — each character responds dynamically using Claude's agent SDK" },
        ],
      }}
    />
  );
}
